apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app1-workload
  description: Ejemplo de despliegue de workload
  tags:
    - java
    - frontend
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=app1-workload"

spec:
  type: service
  lifecycle: experimental
  owner: ipm-team
